### ISSUE TITLE
Add docs to python wrappers

### ISSUE THREAD

**Issue by TomSchammo** [ekut-es/LidarAug#10]
# TODO

- [x] `translate`
- [x] `scale`
- [x] `translate_random`
- [x] `scale_random`
- [x] `flip_random`
- [x] `random_noise`
- [x] `rotate_deg`
- [x] `rotate_rad`
- [x] `rotate_random`
- [x] `scale_random`
- [x] `scale_local`
- [x] `thin_out`
- [x] `delete_labels_by_min_points`
- [x] `fog`
- [x] `fog (overload)`
- [x] `snow`
- [x] `snow (overload)`
- [x] `rain`
- [x] `rain (overload)`
- [x] `local_to_local_transform`
- [x] `local_to_world_transform`
